services:
    
    mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongodb:/data/db 
        environment:
            MONGO_INITDB_ROOT_USERNAME: reist
            MONGO_INITDB_ROOT_PASSWORD: password1234

    backend:
        build: ./backend
        container_name: backend
        restart: unless-stopped
        ports:
            - "5000:5000"
        env_file:
            - ./backend/.env
        depends_on:
            - mongodb

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: auth-app-frontend
        ports:
            - "3000:3000"
        restart: unless-stopped
        env_file:
            - ./frontend/.env
        depends_on:
            - backend
        networks:
            - app-network

    fastapi-weather:
        build: ./fast-api
        container_name: fast-api
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./fast-api/weather.db:/app/weather.db  # SQLite persistente
        networks:
            - app-network

    frontend-puro:
        build: ./frontend-fastapi
        container_name: frontend-fastapi
        restart: unless-stopped
        ports:
            - "8080:80"  # Tu nuevo frontend accesible en localhost:8080
        depends_on:
            - fastapi-weather
        networks:
            - app-network

    mongodb-pokemon:
        image: mongo:6.0
        container_name: mongodb-pokemon
        restart: unless-stopped
        ports:
            - "27018:27017"   # expuesto localmente en 27018 para pruebas
        volumes:
            - mongodb-pokemon-data:/data/db
        networks:
            - app-network

    express-pokemon:
        build: ./express-pokemon
        container_name: express-pokemon
        restart: unless-stopped
        ports:
            - "5001:5000"  # expone 5001 en host → 5000 en contenedor
        env_file:
            - ./express-pokemon/.env
        depends_on:
            - mongodb-pokemon
        networks:
            - app-network
        # Para correr seed automáticamente descomenta esta línea:
        # command: ["sh", "-c", "node seed.js && node server.js"]

    frontend-pokemon:
        build: ./frontend-pokemon
        container_name: frontend-pokemon
        restart: unless-stopped
        ports:
            - "8081:80"  # estará disponible en http://localhost:8081
        depends_on:
            - express-pokemon
        networks:
            - app-network

volumes:
    mongodb:
    mongodb-pokemon-data:

networks:
  app-network:
    driver: bridge
