services:
    mongodb:
        image: mongo:6
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password1234
        volumes:
            - mongodb:/data/db
            - ./mongo-init:/docker-entrypoint-initdb.d:ro
        networks:
            - app-network

    mul-api:
        build: ./mul-API
        container_name: mul-api
        restart: unless-stopped
        ports:
            - "5000:5000"
        env_file:
            - ./mul-API/.env
        depends_on:
            - mongodb
        networks:
            - app-network

    # fastapi-weather:
    #     build: ./fast-api
    #     container_name: fast-api
    #     restart: unless-stopped
    #     ports:
    #         - "8000:8000"
    #     volumes:
    #         - ./fast-api/weather.db:/app/weather.db  # SQLite persistente
    #     networks:
    #         - app-network

    # frontend-puro:
    #     build: ./frontend-cordova/www/clima-fastapi
    #     container_name: frontend-fastapi
    #     restart: unless-stopped
    #     ports:
    #         - "8080:80"  # Tu nuevo frontend accesible en localhost:8080
    #     depends_on:
    #         - fastapi-weather
    #     networks:
    #         - app-network
            
volumes:
    mongodb:
    # fastapi-weather:

 
networks:
  app-network:
    driver: bridge